language: node_js
sudo: required
node_js: 
  - 8.10.0

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm i -g hexo-cli

install:
  - npm i

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "poster"
  - git config user.email "poster@embox.cc"
  - sed -i "s/_token_/${TOKEN}/g" ./_config.yml
  - hexo deploy