title: ITCOOK
subtitle: ITCOOK BLOG
description: 水木IT技术博客
author: shuimu
language: zh-CN
timezone:
url: http://itcook.cc
root: /
permalink: :year/:month/:id.html
permalink_defaults:
# Directory
source_dir: source
public_dir: public
tag_dir: t
pagination_dir: p
index_generator:
  path: ''
  per_page: 10
  order_by: -date

i18n_dir: :lang
skip_render:
  
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
theme: shuimu
deploy:
  type: git
  repo: https://_token_@github.com/shui0mu/shui0mu.github.io.git
  branch: master
